### ISSUE TITLE
Server Crash 1.20.1

### ISSUE THREAD

**Issue by suitun** [cleannrooster/spellblades-1.20.1#5] opened 2023-10-30 11:25 UTC
[crash-2023-10-30_19.17.54-server.txt](https://github.com/cleannrooster/spellblades-1.20.1/files/13204511/crash-2023-10-30_19.17.54-server.txt)

杀了一个魔法师之后好像刷了好几个出来，跟他们打架，然后就再也启动不了服务器了

After killing a magician, it seems that several more appeared. I had a fight with them, and then I couldn't start the server anymore

**Comment by cleannrooster** [comment] 2023-10-31 01:52
Install Neurina to fix it for now, for some reason this seems to happen sometimes, I'm aware of the issue but have no idea how to fix it ATM due to not being able to reproduce it myself.

**Comment by suitun** [comment] 2023-10-31 11:50
Thank you. It was my first time getting to know Neurina, and that was a great mod! I used to solve the server crash caused by Ticking Entity by deleting the block where the entity was located through MCA Selector.

**Comment by cleannrooster** [comment] 2023-10-31 15:24
As for the underlying issue, I believe I have fixed it as of the recent update. Closing.

**Closed as completed by cleannrooster** 2023-10-31 15:24 UTC
